refactor(meta): sleep a second before removing dir when cleaning up sled during upgrade
NFS may hold the resource for longer thus there might be an error such
as:

```
Error: std::io::error::Error: std::io::error::Error: Device or resource busy (os error 16);
    when:(remove dir /var/lib/databend/raft/heap;
    when remove V003 raft-log store based on sled: '/var/lib/databend/raft')
```